### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by Dom-Mc** [learn-co-curriculum/angular-using-scope-apply-lab#10]
There appears to be an open issue from April.  For anyone else running into this problem, check out this thread for a way to get around it:
https://github.com/learn-co-students/angular-using-scope-apply-lab-v-000/issues/17#issuecomment-249617544

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/angular-using-scope-apply-lab/commit/76ee56999cc437141af698eba93d2bcfd22fa9a7.

Sorry about that @Dom-Mc !
